### ISSUE TITLE
Generating a deep link with URI params

### ISSUE THREAD

**Issue by vinnyhoward** [AppsFlyerSDK/react-native-appsflyer#99]
I have an issue where I can't pass custom params into my apps URI. I can only get this URI `exampleapp://` but I want to be able to add custom params to it such as `exampleapp://product/23` so I can generate a deep link, send this to another user, and this user would be routed to the corresponding product.

I am trying to use `appsflyer.setAppInviteOneLinkID` and `appsflyer.generateInviteLink` but the options available in the docs of this repo gives me no results. Help would be GREATLY appreciated.

**Comment by wesfieldj** [comment]
@vinnyhoward can you provide a code snippet of your setAppInviteOneLinkID and generateInviteLink methods?

**Comment by vinnyhoward** [comment]
@wesfieldj Yeah for sure!

```
    generateGiftDeepLink: () => async () => {
      // "Appsflyer.generateInviteLink" Still does not work, still unable to pass custom params in URI
      // I created a issue for it on their repository https://github.com/AppsFlyerSDK/react-native-appsflyer/issues/99
      Appsflyer.setAppInviteOneLinkID('aCHT', success => console.log(success));

      const inviteOptions = {
        parameter: 'hello',
        af_dp: 'sup',
        userParams: {
          myParam: 'newUser',
          anotherParam: 'fromWeb',
          amount: 1,
        },
      };
      
      const onInviteLinkSuccess = link => {
        console.log(link);
        return link;
      };
      
      const onInviteLinkError = err => {
        console.log(err);
      };
      
      Appsflyer.generateInviteLink(inviteOptions, onInviteLinkSuccess, onInviteLinkError).then(res => console.log('res:', res));
    },
  })
);
```

I basically tested a bunch different params to see what sticks, but I would get nothing back in my params. Just my main deep link uri of `exampleapp://`

I also tried out the example one of course from the repo docs of course
```
var inviteOptions {
  channel: 'gmail',
  campaign: 'myCampaign',
  customerID: '1234',
  userParams {
    myParam: 'newUser',
    anotherParam: 'fromWeb',
    amount: 1
  }
};

var onInviteLinkSuccess = function(link) {
  console.log(link); // Handle Generated Link Here
}

function onInviteLinkError(err) {
  console.log(err);
}

appsFlyer.generateInviteLink(inviteOptions, onInviteLinkSuccess, onInviteLinkError);
``` 

Same results. I hope this helps

**Comment by wesfieldj** [comment]
@vinnyhoward What version of the plugin are you using? 
If you are using a version < 1.4.3 then please upgrade to v1.4.3 and the issue should be solved!

There was a bug in the previous versions and it was recently fixed and published. 
https://github.com/AppsFlyerSDK/react-native-appsflyer/commit/789dd38178472a03c0e3d2f8b470d7945d960d3d

Please let us know if you are still facing the same issue after upgrading. 

Thanks!

**Comment by vinnyhoward** [comment]
Thanks for looking into it, I really appreciate it. I was in fact using `1.4.2` I just upgraded to `"react-native-appsflyer": "^1.4.3",`. I tried the example values again and a few other ones to see if I could get anything, but I still get the base URI only.

I was excited that hopefully this was just a simple upgrade issue, but it seems like its not :(

**Comment by wesfieldj** [comment]
@vinnyhoward We are not sure why this would no be working after the upgrade. 

We just tested this on our end and we were able to generate the link successfully. 

Here is the code we used: (v1.4.3)

``` javascript
generateInviteLink = () => {
    appsFlyer.setAppInviteOneLinkID("abcd" , (success)=>{console.log(success)});
    appsFlyer.generateInviteLink(
      {
        channel: 'gmail',
        campaign: 'myCampaign',
        customerID: '1234',
        userParams: {
          myParam: 'newUser',
          anotherParam: 'fromWeb',
          amount: 1,
        },
      },
      (link) => {
        console.log( 'AppsFlyer_' + link);
      },
      (err) => {
        console.log(err);
      }
     );
  };
```

Which generate the link:

```
https://go.onelink.me/abcd?pid=af_app_invites&amount=1&af_referrer_customer_id=1234&c=myCampaign&anotherParam=fromWeb&myParam=newUser&af_referrer_uid=1563783869884-8333716823092316089&af_channel=gmail&af_siteid=com.afexample
```

If you still can not get it working please reach out to the AppsFlyer Support Team by emailing support@appsflyer.com. You can add the link to the GitHub issue in the email. 
They will be able to provide you with more direct and comprehensive support.

**Comment by vinnyhoward** [comment]
@wesfieldj So I was able to produce a link just link yours with my app, which is great.

`https://www.vinsent.wine/?myParam=newUser&pid=af_app_invites&referrer_af_id=1563803921480-1035123&shortlink=d40bbeea&af_referrer_customer_id=1234&amount=1&af_channel=gmail&anotherParam=fromWeb&af_siteid=1449458803&c=myCampaign`

But I would also want to pass those same params via mobile URI. For example if were just dealing with the amount part of the params. I would like to get back `exampleapp://amount/1` but I still only get `exampleapp://` within my app.

Maybe I have misinterpreted what the functions would do, so do the params get only passed via web link? I was under the impression that it would be able to translate to a mobile URI and a mobile link. For example creating a deep link with 

Thank you for answering my questions. I will email support and try to find out more

**Comment by vinnyhoward** [comment]
I contacted support and they gave me the info I needed in order to pass URI params to the app. Passing `baseDeepLink` and its contents to `generateInviteLink`will give you params inside your deep link.

The docs say refer to the AppsFlyer docs on their site for more parameters but it looks like the parameters for React Native vs iOS/Android are not the same.

@wesfieldj thanks again for all your help btw!
